### ISSUE TITLE
independent values without dependent values will also be returned

### ISSUE THREAD

**Issue by tcstory** [mmikowski/urianchor#7]
my English is poor.
i run the following command
```
$.uriAnchor.setAnchor({
  page : 'profile',
  _page : {
    uname   : 'wendy',
    online  : 'true'
  },
  slider  : 'confirm',
  _slider : {
   text   : 'hello',
   pretty : false
  },
  color : 'red'
});
```

but in my firefox 37 and chrome 41, _s_color is also returned? is this a bug?

![snapshot2](https://cloud.githubusercontent.com/assets/5856466/7105191/db040d84-e13f-11e4-8d6f-69fcc385c7c2.png)
![snapshot3](https://cloud.githubusercontent.com/assets/5856466/7105208/802b435e-e140-11e4-84e5-977a7c126496.png)

**Comment by mmikowski** [comment]
No, this is not a bug.  It is actually a feature.  It provides a way to easily see if any part of an independent variable group has changed.

**Comment by tcstory** [comment]
thank you~!

**Comment by refanbanzhang** [comment]
wow!

**Comment by refanbanzhang** [comment]
围观

**Comment by chengchenghe** [comment]
给力了,看了这本书,学到更多的是作者的思维想法与解决问题的思路.

Awesome, look at this book, more is the author's thoughts and ideas to solve the problem to learn.

**Comment by refanbanzhang** [comment]
这本书真的是叼炸天
