### ISSUE TITLE
Listener

### ISSUE THREAD

**Issue by dylanmac** [mmikowski/urianchor#9]
Do you recommend a listener to use in conjunction?

**Comment by dylanmac** [comment]
Hello?

**Comment by mmikowski** [comment]
Sorry for the delay.  A listener to use with URI Anchor:

     $(window).bind( 'hashchange', onHashChange );

See a full example here:
https://github.com/mmikowski/spa/tree/master/listings/ch05_06/6.5

To see it running, make a dereferenced copy of the directory and open the webpage:

    cp -aL 6.5 6.5dr
    cd 6.5dr
    google-chrome spa.html
    // Remember to log in as "fred" to make it possible to open and close the chat window

I hope that helps.  I will add this to the README; if this works for you, can we close the issue?

**Comment by dylanmac** [comment]
Thank you.
